# native-helper-graalvm generation configuration
---
createParentDirectory: true
generate:
  - className: io.github.caffetteria.nmd.Persona
    mode: getters
  - className: io.github.caffetteria.nmd.Ruolo
    mode: getters